// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjhCOarNsWE9FWR6fRybMTpRPvuGoUXG8',
    appId: '1:142542064295:web:062c56f84c58fa56eb2982',
    messagingSenderId: '142542064295',
    projectId: 'quotes-ba1c5',
    authDomain: 'quotes-ba1c5.firebaseapp.com',
    storageBucket: 'quotes-ba1c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzadRtP6a_vj8Grtg9DVnI486tzxgTX4M',
    appId: '1:142542064295:android:a91651ef3c0cd291eb2982',
    messagingSenderId: '142542064295',
    projectId: 'quotes-ba1c5',
    storageBucket: 'quotes-ba1c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAAXnca9fhTwsIq6SIcS7Ttyl_3V34yTQ',
    appId: '1:142542064295:ios:85f11c428ac87b6feb2982',
    messagingSenderId: '142542064295',
    projectId: 'quotes-ba1c5',
    storageBucket: 'quotes-ba1c5.firebasestorage.app',
    iosBundleId: 'com.example.randomQuote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAAXnca9fhTwsIq6SIcS7Ttyl_3V34yTQ',
    appId: '1:142542064295:ios:85f11c428ac87b6feb2982',
    messagingSenderId: '142542064295',
    projectId: 'quotes-ba1c5',
    storageBucket: 'quotes-ba1c5.firebasestorage.app',
    iosBundleId: 'com.example.randomQuote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjhCOarNsWE9FWR6fRybMTpRPvuGoUXG8',
    appId: '1:142542064295:web:4ab4e4fdcb035a32eb2982',
    messagingSenderId: '142542064295',
    projectId: 'quotes-ba1c5',
    authDomain: 'quotes-ba1c5.firebaseapp.com',
    storageBucket: 'quotes-ba1c5.firebasestorage.app',
  );
}
